<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>LedgerKit.AvaloniaSpike.Benchmarks</AssemblyName>
    <RootNamespace>LedgerKit.AvaloniaSpike.Benchmarks</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/LedgerKit.AvaloniaSpike.Core/LedgerKit.AvaloniaSpike.Core.csproj" />
  </ItemGroup>
</Project>
